apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-science-3a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-science-3a
  template:
    metadata:
      labels:
        app: data-science-3a
    spec:
      containers:
      - name: data-science-3a
        image: uk4zor/data-science-3a:latest
        ports:
        - containerPort: 80
