apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-science-app
  labels:
    app: data-science-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: data-science-app
  template:
    metadata:
      labels:
        app: data-science-app
    spec:
      containers:
      - name: data-science-container
        image: uk4zor/data-science-3a:latest 
        ports:
        - containerPort: 80
