apiVersion: v1
kind: Service
metadata:
  name: data-science-service
spec:
  selector:
    app: data-science-app
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 80  
  type: ClusterIP  
